name: easy_postgresql

services:
  postgresql:
    image: ${POSTGRES_IMAGE:-docker.io/library/postgres:17}
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
