services:
  pg:
    image: docker.io/library/postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/sock:/var/run/postgresql
