name: compose_pg

services:
  postgresql:
    image: ${POSTGRES_IMAGE}
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
